### PR TITLE
Added better color handling, xdcc_store upated

### PR DESCRIPTION
**Pull request by Totto16**
The color Handling was just some characters here and there, so I added all available Colors and ControlChars according to the docs. 
Also the xdcc_store is outdated, since HorribleSubs doesn't provide any packages, so I added the new SubsPlease one.
The color codes are "invisible" on Github, but with an IDE you actually see the Control Characters they represent

### CODE REVIEW

**Comment by Chronoes** [comment]
Hello! Thank you for the contribution. Surprised to see someone else actually using it.

I have a question about the changes in `xdcc_store.json`. Is the HTTP method working for you? While it's true that HorribleSubs is discontinued and SubsPlease took over, they later also added CloudFlare protection which prevents the querying of the packlist over HTTP.  In PR #38 the option to use bot's packlist was developed instead which I use. If we're updating the config then I would recommend to use that for the defaults.

Also, please refactor the function and variable names to be PEP 8 compatible (snake_case) like the rest of the codebase.

**Comment by Totto16** [comment]
True, the Cloudfare protection is in the way
and I wi'll do that :)

**Comment by Totto16** [comment]
And One question, how to set that option, to retrieve the list from the bot, I can see it in the code, that the option exists, but I am not able to find an option for 'metaType'

**Comment by Chronoes** [comment]
> And One question, how to set that option, to retrieve the list from the bot, I can see it in the code, that the option exists, but I am not able to find an option for 'metaType'

True, there's a lack of documentation on that part. The condition is to not have the "url" key in the packlist config.

**Comment by Totto16** [comment]
I also added some MENU entries, so its easier to run some tasks in the GUI, for now only realod and cheking a packlist manually

**Pull request merged**
